name: Validação do Python

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r src/python/requirements.txt
    - name: Analisando o código com pylint
      run: |
        pylint src/python/**/*.py
    - name: Execução dos testes
      run: |
        pytest src/python
    - name: Verificação automática do formato do código
      run: |
        autopep8 --recursive --diff --aggressive --aggressive src/python
